###########################################################################
# This is the sample config file for the DataPlotBot Application. It contains the 
# twitter keys for the bot and other configuration parameters used by the app
###########################################################################

author:
  name: Rupali Mayekar
  
project:
  name: DataPlotBot
  language: python

keys:
  # Twitter API Keys generated for the app
  plotbot_consumer_key : "ENTER YOUR APP'S CONSUMER KEY HERE"
  plotbot_consumer_secret : "ENTER YOUR APP'S CONSUMER SECRET HERE"
  plotbot_access_token : "ENTER YOUR APP'S ACCESS TOKEN HERE"
  plotbot_access_token_secret : "ENTER YOUR APP'S ACCESS TOKEN SECRET HERE"

constants:
  # If you wish to use this app for your bot, then you may change this to specify your twitter screen name
  # For example: BOT_STR : "@DataPlotBot Analyze:"    
  BOT_STR = "ENTER YOUR TWITTER SCREEN NAME MENTION STRING HERE"    
  